version: 2

sources:
  - name: reference
    database: stewart
    schema: tpcdi_sf10
    loader: Python

    tables:
      - name: status_type
      - name: industry
      - name: date
      - name: tax_rate
      - name: trade_type