version: 2

sources:
  - name: brokerage
    database: stewart
    schema: tpcdi_sf10
    loader: Python

    tables:
      - name: daily_market
      - name: watch_history
      - name: trade
      - name: trade_history
      - name: holding_history
      - name: cash_transaction
      
